source 'https://rubygems.org'

gem 'rails', '4.1.8'
gem 'sqlite3'
#gem 'mysql2'
gem 'social-share-button'
gem 'metamagic'
gem 'canonical-rails', github: 'jumph4x/canonical-rails'
gem 'mini_magick'

## Markdown editor
gem 'simditor',github: 'brucebot/simditor-rails'
#头像
gem 'letter_avatar',github: 'brucebot/letter_avatar'
gem 'friendly_id',github: 'brucebot/friendly_id'
gem 'chinese_pinyin'
gem 'ruby-pinyin'
#Markdown
gem 'redcarpet'
gem 'reverse_markdown','0.8.2'

#认证码
gem 'rucaptcha'
gem 'randomstring'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0',          group: :doc

#assets
gem 'therubyracer'
gem 'coffee-rails'
gem 'sass-rails', '~> 4.0.3'
gem 'uglifier', '>= 1.3.0'
gem 'yui-compressor'
gem "font-awesome-rails"
gem 'simple_form'
gem 'nprogress-rails'
gem "less-rails" #Sprockets (what Rails 3.1 uses for its asset pipeline) supports LESS
gem "twitter-bootstrap-rails"
gem 'jquery-rails'
gem 'turbolinks'
gem 'jquery-turbolinks'

#mobile detector
gem 'browser'

#分页
gem 'kaminari'

#自载加载
gem 'jquery-infinite-pages'

#视频上传
gem 'videojs_rails'
gem 'carrierwave-video-thumbnailer'
gem 'streamio-ffmpeg'
gem 'carrierwave','1.3.2'
gem 'rest-client'
gem 'carrierwave-aliyun'
gem 'carrierwave-qiniu',:git=>"git://github.com/huobazi/carrierwave-qiniu.git"
gem 'qiniu'


##pdf 处理
gem 'pdfjs_rails'
#认证
gem 'devise-i18n'
gem 'devise',           '~> 3.5.2'

# Server
gem "passenger"

#缓存
gem 'super_cache'

# Syntax highlighter
gem 'rouge'
gem 'auto-space'

group :development do
	#调试
	gem 'pry-rails'
	#优化
	gem "rails_best_practices"
	gem 'traceroute'

	#
	gem 'fabrication'
	gem 'faker'
	gem 'brakeman', :require => false

end
